### ISSUE TITLE
Error in x %*% betas

### ISSUE THREAD

**Issue by jodyphelan** [afrahshafquat/phelex#1]
Thanks for creating this library I think it will super useful for me! I am trying to use the library but I'm running to an error:

```
> phelex.results = phelex(x = x,
+                         y = y,
+                         A = A,
+                         alpha.prior = c(10, 1), # Beta prior for true-positive rate
+                         iterations = 1e5)
Error in x %*% betas : requires numeric/complex matrix/vector arguments
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

Any ideas on where it could have gone wrong?

Thanks,
Jody

**Comment by afrahshafquat** [comment]
Can you send the dimensions of the matrix x?

**Comment by jodyphelan** [comment]
```
> dim(x)
[1]    40 18676
```

**Comment by afrahshafquat** [comment]
dimensions of x should be samples (rows) x snps (columns) such that dimensions of A are samples x samples. So in your case A should have dimensions 40x40. Is that correct?

**Comment by afrahshafquat** [comment]
please let me know if this issue was resolved or if you are still getting the error.
Thanks!
